---
- name: See if ifupdown is installed
  command: apt list --installed | grep ifupdown
  register: apt_check
  ignore_errors: true

- block:
    - name: install ifupdown
      apt: pkg=ifupdown state=present

    - name: install ifenslave
      apt: pkg=ifenslave state=present

    - name: install ifenslave
      apt: pkg=ifenslave state=present

    - name: ensure module is loaded 
      command: modprobe bonding
    
    - name: unmask networking
      command: systemctl unmask networking

    - name: enable networking
      command: systemctl enable networking
    
    - name: stop old service
      command: systemctl stop systemd-networkd.socket networkd.dispatcher systemd-networkd-wait-online 
      ignore_errors: true

    - name: disable old service
      command: systemctl disable systemd-networkd.socket networkd.dispatcher systemd-networkd-wait-online 
      ignore_errors: true

    - name: mask old service
      command: systemctl mask systemd-networkd.socket networkd.dispatcher systemd-networkd-wait-online 
      ignore_errors: true

    - name: remove netplan packages
      command: apt-get --assume-yes purge nplan netplan.io

    - name: ensure modules file has bonding
      ansible.builtin.lineinfile:
        path: /etc/modules
        line: bonding
        create: yes
  when: apt_check is failed

- name: install ifenslave
  apt: pkg=ifenslave state=present

- name: make sure interfaces file is current update if it is different
  copy: src=interfaces dest=/etc/network/interfaces force=yes
